In [5]:
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 11 14:24:32 2019

@author: Mohammad Daneshvar
"""

import numpy as np
import random


def kmeans(X, Xnew, num_clus, num_iter):
    
    cluster = random.choices(X, k = num_clus)
    m = np.shape(X)[0] 
    
    for iteration in range(num_iter):
        
        # Assign the closest cluster to each sample
        index = []    
        for i in range(m):
            distances = []
            for j in range(num_clus):
                distance = np.dot((X[i]-cluster[j]), (X[i]-cluster[j]))
                distances.append(distance)
            index.append(np.argmin(distances))
            
        # Move clusters to the average of their assigned samples
        for j in range(num_clus):
            assigned_samples = []
            for i in range(m):
                if index[i] == j:
                    assigned_samples.append(X[i])
            cluster[j] = np.mean(assigned_samples, axis=0) 
            
    # Now predict new samples  
    new_index = []
    for i in range(len(Xnew)):
        new_distances = []
        for j in range(num_clus):
            new_distance = np.dot((Xnew[i]-cluster[j]), (Xnew[i]-cluster[j]))
            new_distances.append(new_distance)
        new_index.append(np.argmin(new_distances)) 
   
    return [index, cluster, new_index]


X = np.array([[4,5],[-2,-3],[3,4],[-5,4],[-4,-3],[4,6],[3,2],[-3,3]])
Xnew = np.array([[3,2],[1,-1],[-1,1],[-2,-2]]) 
num_clus = 2
num_iter = 1000

[index, cluster, new_index] = kmeans(X, Xnew, num_clus, num_iter)  
print('Samples =\n', X, '\n')
print('Number of Clusters =', num_clus, '\n')
print('Class of samples X =', index, '\n')
print('Location of clusters =\n', np.matrix(cluster), '\n')
print('New samples =\n', Xnew, '\n')
print('Class of new samples = ', new_index)


Samples =
 [[ 4  5]
 [-2 -3]
 [ 3  4]
 [-5  4]
 [-4 -3]
 [ 4  6]
 [ 3  2]
 [-3  3]] 

Number of Clusters = 2 

Class of samples X = [0, 1, 0, 1, 1, 0, 0, 1] 

Location of clusters =
 [[ 3.5   4.25]
 [-3.5   0.25]] 

New samples =
 [[ 3  2]
 [ 1 -1]
 [-1  1]
 [-2 -2]] 

Class of new samples =  [0, 1, 1, 1]


As we can see in this simple yet interesting clustering, points $(x,y)$ where $x>0$ and $y>0$ are labeled 0 and others are labeled 1.